title: Conference for Energy Students (CES)
shorttitle: CES
preposition: at
description: >-
   Hosted by Department of Energy, Aalborg University
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ces.energy.aau.dk" # the base hostname & protocol for your site, e.g. https://example.com

tree_url: 'https://github.com/jakobhaervig/ces/raw/main'
abstract_template: '/templates/CES_abstract_template.zip'
poster_template: '/templates/CES_poster_template.pptx'

theme: jekyll-theme-conference

# Build settings
markdown: kramdown
sass:
  style: compressed

# Additional exclude from processing
exclude:
  - vendor
  - .github/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - purgecss.config.js

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/
  number:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room


conference:

  # Language
  lang: en

  # Show theme errors:
  show_errors: True

  # Navigation bar
  navigation:
    logo:
      name: Aalborg University
      img: 'logo_aau.svg'  # inside /assets/images/
      url: 'https://aau.dk/'
    breakpoint: md
    links:
      - name: Programme
        relative_url: /program/
      - name: Talks
        relative_url: /talks/
      - name: Location
        relative_url: /location/
      - name: Important Information
        relative_url: /information/
      - name: Previous Editions
        menu:
          - name: 2024 (current)
            disabled: true
          # - name: 2023
          #   relative_url: /2023/

  # Link Preview for Sharing
  link_preview:
    # also adapt "preposition" property at top for more meaningful descriptions
    disable: false
    img:
      twitter: 'twitter_preview.png'      # inside /assets/images/
      open_graph: 'facebook_preview.png'  # inside /assets/images/

  # Main landing page
  main:
    logo:
       img: 'ces_picture.jpeg'  # inside /assets/images/
    links:
      - name: Programme
        relative_url: /program/
      - name: Conference venue
        relative_url: /location/
      - name: Important information and dates
        relative_url: /information/
  # Information boxes
  info_bars:
    - title: Welcome to the new website of CES 2024!
      color: primary
      main_only: true
      text: |
        **Update**: Submission of abstract and poster has changed. Follow the links under "Important information" to submit in Moodle.

  # Live indications
  live:
    date: 19.08.2024
    timezone: GMT+1
    stop:       240  # in minutes
    streaming:
      enable: true
      pause:     60  # in minutes
      prepend:    5  # in minutes
      extend:     5  # in minutes
    demo:
      enable: false
      duration: 300  # in seconds
      pause:     10  # in seconds

  talks:
    # Talk categories
    main_categories:
      - name: Session 1A
        chairman: 'John Doe'
        color: primary
      - name: Session 2A
        color: secondary
      - name: Session 3A
        color: success
      - name: Session 4A
        color: info
      - name: Session 1B
        color: pink
      - name: Session 2B
        color: danger
      - name: Session 3B
        color: light
      - name: Session 4B
        color: dark
      - name: Plenary
        color: warning

    # Hide icons on talk overview page
    hide_icons: false

  speakers:
    # Show first and last name
    show_firstname: true

  location:
    # Disable links to locations
    hide: false
    # URL of location / room overview page
    url: '/location'
    # Main page title shown on location/room navigation bar
    navbar_title: 'Location'
    # Show map on location main page.  Set `map: false` if you don't want to
    # display it.
    map:
      # Initial map center point
      home_coord: 57.0157388,9.9729215
      # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
      # The following do match the Bootstrap design not too badly:
      #   - Thunderforest.Neighbourhood
      #   - Esri.WorldTopoMap
      map_provider: "OpenStreetMap.Mapnik"
      default_zoom: 17


  program:
    # URL of program page
    url: '/program'

    # Time steps in program table
    time_steps: 15 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: true
